/**
 * BibTeX Generator Service
 * Generates BibTeX entries from paper data for use in LaTeX documents
 */
import fs from 'fs';
import logger from '../core/logger';

interface Paper {
  title: string;
  authors?: string;
  year?: number;
  abstract?: string;
  url?: string;
  source?: string;
  publisher?: string;
  [key: string]: any;
}

export class BibTeXGenerator {
  /**
   * Clean string for BibTeX entry
   */
  static cleanStringForBibtex(text: string): string {
    if (!text) return '';

    // Remove/replace problematic characters
    return text
      .replace(/[{}]/g, '')
      .replace(/\\/g, '')
      .replace(/~/g, ' ')
      .trim();
  }

  /**
   * Generate a BibTeX citation key from title and year
   */
  static generateCitationKey(title: string, year?: number, index: number = 0): string {
    if (!title) {
      return `paper${year || 'Unknown'}_${index}`;
    }

    // Get first meaningful word from title
    const words = title.toLowerCase().match(/\b\w+\b/g) || [];
    const firstWord = words.find((w) => w.length > 3) || words[0] || 'paper';

    // Create base key
    let key = `${firstWord.charAt(0).toUpperCase() + firstWord.slice(1)}${year || 'Unknown'}`;

    // Add suffix if index provided
    if (index > 0) {
      const suffix = String.fromCharCode(97 + index); // a, b, c, etc.
      key += suffix;
    }

    return key;
  }

  /**
   * Generate a BibTeX entry for a single paper
   */
  generateBibtexEntry(paper: Paper, citationKey?: string): string {
    const title = BibTeXGenerator.cleanStringForBibtex(paper.title || '');
    const authors = BibTeXGenerator.cleanStringForBibtex(paper.authors || '');
    const year = paper.year;
    let abstract = BibTeXGenerator.cleanStringForBibtex(paper.abstract || '');
    const url = paper.url || '';
    const source = BibTeXGenerator.cleanStringForBibtex(paper.source || '');
    const publisher = BibTeXGenerator.cleanStringForBibtex(paper.publisher || '');

    // Generate citation key if not provided
    if (!citationKey) {
      citationKey = BibTeXGenerator.generateCitationKey(title, year);
    }

    // Determine entry type (default to article)
    const entryType = 'article';

    // Build BibTeX entry
    const lines = [`@${entryType}{${citationKey},`, `  title = {${title}},`];

    if (authors) {
      lines.push(`  author = {${authors}},`);
    }

    if (year) {
      lines.push(`  year = {${year}},`);
    }

    if (source) {
      lines.push(`  journal = {${source}},`);
    }

    if (publisher) {
      lines.push(`  publisher = {${publisher}},`);
    }

    if (abstract) {
      // Truncate very long abstracts
      if (abstract.length > 500) {
        abstract = abstract.substring(0, 500) + '...';
      }
      lines.push(`  abstract = {${abstract}},`);
    }

    if (url) {
      lines.push(`  url = {${url}},`);
    }

    // Add note about retrieval
    lines.push(`  note = {Retrieved from Google Scholar}`);

    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Generate a complete BibTeX file from a list of papers
   */
  generateBibtexFile(papers: Paper[], outputPath?: string): string {
    if (!papers || papers.length === 0) {
      logger.warn('No papers provided for BibTeX generation');
      return '';
    }

    const content: string[] = [];

    // Header
    content.push('% BibTeX entries generated by LitRevTool');
    content.push('% ' + '='.repeat(70));
    content.push('');

    // Track used citation keys to handle duplicates
    const usedKeys = new Set<string>();

    for (let i = 0; i < papers.length; i++) {
      const paper = papers[i];
      const title = paper.title || '';
      const year = paper.year;

      // Generate unique citation key
      let citationKey = BibTeXGenerator.generateCitationKey(title, year, 0);
      let suffixIndex = 0;

      while (usedKeys.has(citationKey)) {
        suffixIndex++;
        citationKey = BibTeXGenerator.generateCitationKey(title, year, suffixIndex);
      }

      usedKeys.add(citationKey);

      // Generate entry
      const entry = this.generateBibtexEntry(paper, citationKey);
      content.push(entry);
      content.push(''); // Blank line between entries
    }

    // Footer
    content.push(`% Total entries: ${papers.length}`);

    const fullContent = content.join('\n');

    // Save to file if path provided
    if (outputPath) {
      try {
        fs.writeFileSync(outputPath, fullContent, 'utf-8');
        logger.info(`BibTeX file saved to ${outputPath}`);
      } catch (error) {
        logger.error('Error saving BibTeX file:', error);
      }
    }

    return fullContent;
  }
}

/**
 * Convenience function to generate BibTeX file
 */
export function generateBibtexFile(papers: Paper[], outputPath?: string): string {
  const generator = new BibTeXGenerator();
  return generator.generateBibtexFile(papers, outputPath);
}
