"""
BibTeX Generator Service

Generates BibTeX entries from paper data for use in LaTeX documents.
"""

import logging
import re
from typing import List, Dict

logger = logging.getLogger(__name__)


class BibTeXGenerator:
    """Generates BibTeX entries from paper data."""

    @staticmethod
    def clean_string_for_bibtex(text: str) -> str:
        """
        Clean string for BibTeX entry.

        Args:
            text: Input text

        Returns:
            Cleaned text safe for BibTeX
        """
        if not text:
            return ""

        # Remove/replace problematic characters
        text = text.replace('{', '').replace('}', '')
        text = text.replace('\\', '')
        text = text.replace('~', ' ')

        return text.strip()

    @staticmethod
    def generate_citation_key(title: str, year: int, index: int = 0) -> str:
        """
        Generate a BibTeX citation key from title and year.

        Args:
            title: Paper title
            year: Publication year
            index: Index for disambiguation

        Returns:
            Citation key like "FirstWord2023" or "FirstWord2023a"
        """
        if not title:
            return f"paper{year}_{index}"

        # Get first meaningful word from title
        words = re.findall(r'\b\w+\b', title.lower())
        first_word = next((w for w in words if len(w) > 3), words[0] if words else "paper")

        # Create base key
        key = f"{first_word.capitalize()}{year if year else 'Unknown'}"

        # Add suffix if index provided
        if index > 0:
            suffix = chr(97 + index)  # a, b, c, etc.
            key += suffix

        return key

    def generate_bibtex_entry(self, paper: Dict, citation_key: str = None) -> str:
        """
        Generate a BibTeX entry for a single paper.

        Args:
            paper: Paper dictionary with title, authors, year, etc.
            citation_key: Optional citation key, will be generated if not provided

        Returns:
            BibTeX entry as string
        """
        title = self.clean_string_for_bibtex(paper.get('title', ''))
        authors = self.clean_string_for_bibtex(paper.get('authors', ''))
        year = paper.get('year')
        abstract = self.clean_string_for_bibtex(paper.get('abstract', ''))
        url = paper.get('url', '')
        source = self.clean_string_for_bibtex(paper.get('source', ''))
        publisher = self.clean_string_for_bibtex(paper.get('publisher', ''))

        # Generate citation key if not provided
        if not citation_key:
            citation_key = self.generate_citation_key(title, year)

        # Determine entry type (default to article)
        entry_type = "article"

        # Build BibTeX entry
        bibtex_lines = [
            f"@{entry_type}{{{citation_key},",
            f"  title = {{{title}}},"
        ]

        if authors:
            bibtex_lines.append(f"  author = {{{authors}}},")

        if year:
            bibtex_lines.append(f"  year = {{{year}}},")

        if source:
            bibtex_lines.append(f"  journal = {{{source}}},")

        if publisher:
            bibtex_lines.append(f"  publisher = {{{publisher}}},")

        if abstract:
            # Truncate very long abstracts
            if len(abstract) > 500:
                abstract = abstract[:500] + "..."
            bibtex_lines.append(f"  abstract = {{{abstract}}},")

        if url:
            bibtex_lines.append(f"  url = {{{url}}},")

        # Add note about retrieval
        bibtex_lines.append(f"  note = {{Retrieved from Google Scholar}}")

        bibtex_lines.append("}")

        return "\n".join(bibtex_lines)

    def generate_bibtex_file(self, papers: List[Dict], output_path: str = None) -> str:
        """
        Generate a complete BibTeX file from a list of papers.

        Args:
            papers: List of paper dictionaries
            output_path: Optional path to save the file

        Returns:
            Complete BibTeX content as string
        """
        if not papers:
            logger.warning("No papers provided for BibTeX generation")
            return ""

        bibtex_content = []

        # Header
        bibtex_content.append("% BibTeX entries generated by LitRevTool")
        bibtex_content.append("% " + "=" * 70)
        bibtex_content.append("")

        # Track used citation keys to handle duplicates
        used_keys = set()

        for i, paper in enumerate(papers):
            title = paper.get('title', '')
            year = paper.get('year')

            # Generate unique citation key
            base_key = self.generate_citation_key(title, year, 0)
            citation_key = base_key
            suffix_index = 0

            while citation_key in used_keys:
                suffix_index += 1
                citation_key = self.generate_citation_key(title, year, suffix_index)

            used_keys.add(citation_key)

            # Generate entry
            entry = self.generate_bibtex_entry(paper, citation_key)
            bibtex_content.append(entry)
            bibtex_content.append("")  # Blank line between entries

        # Footer
        bibtex_content.append(f"% Total entries: {len(papers)}")

        full_content = "\n".join(bibtex_content)

        # Save to file if path provided
        if output_path:
            try:
                with open(output_path, 'w', encoding='utf-8') as f:
                    f.write(full_content)
                logger.info(f"BibTeX file saved to {output_path}")
            except Exception as e:
                logger.error(f"Error saving BibTeX file: {e}")

        return full_content


def generate_bibtex_file(papers: List[Dict], output_path: str = None) -> str:
    """
    Convenience function to generate BibTeX file.

    Args:
        papers: List of paper dictionaries
        output_path: Optional path to save the file

    Returns:
        BibTeX content as string
    """
    generator = BibTeXGenerator()
    return generator.generate_bibtex_file(papers, output_path)
